#!/bin/bash
dayFile="Day0"
programDayFile="ProgramDay0"
dayTestFile="Day0KtTest"
year="$1"

testKotlin="../src/test/kotlin/adventofcode${year}"
resources="../src/main/resources/adventofcode${year}"
kotlin="../src/main/kotlin/adventofcode${year}"

mkdir $testKotlin
mkdir $resources
mkdir $kotlin

counter=1
while ((counter!=26))
do
  touch "${resources}/day${counter}.txt"
  ./createSource $year $counter $kotlin $dayFile
  ./createSource $year $counter $kotlin $programDayFile
  ./createSource $year $counter $testKotlin $dayTestFile
	((counter+=1))
done
exit 0
